### ISSUE TITLE
It won't unzip on macOS

### ISSUE THREAD

**Issue by LEOYoon-Tsaw** [adobe-fonts/source-han-super-otc#1]
The zip files are not recognizable on macOS by the default zipping tool nor Entropy. Is there any way to extract the otc file on macOS?

**Comment by kenlunde** [comment]
@LEOYoon-Tsaw: You are correct, but this is explicitly stated in the paragraph that follows the three download links:

![unarchiver-app](https://cloud.githubusercontent.com/assets/3988788/25337329/50e5a738-28b0-11e7-84d4-ced346459506.jpg)
