### ISSUE TITLE
Simplified Chinese of README.md

### ISSUE THREAD

**Issue by DrXie** [adobe-fonts/source-han-super-otc#3]
# 下载 Source Han Super OTC

Adobe 品牌的 Source Han Sans, Source Han Serif 和 Source Han Code JP，以及 Google 品牌的 Noto Sans CJK 和 Noto Serif CJK，都是遵循 [SIL开源字体授权 1.1 版](http://scripts.sil.org/OFL) 的基于 CID 的 OpenType/CFF 泛中日韩及日本（Source Han Code JP）字体（另见 [授权](LICENSE.txt) 和 [常见问题集](http://scripts.sil.org/cms/scripts/page.php?item_id=OFL-FAQ_web)）。

在这个项目中你将找到三个包含各对应五款字体的 64、78 或 142 个字体的即装的 OpenType/CFF 集合（即 Super OTC）。

这个 Super OTC 的组合包含 36 个字体的 [Source Han Sans OTFs](https://github.com/adobe-fonts/source-han-sans/tree/release/OTF)，28 个字体的 [Source Han Serif OTFs]((https://github.com/adobe-fonts/source-han-serif/tree/release/OTF),)，14 个字体的 [Source Han Code JP OTFs]((https://github.com/adobe-fonts/source-han-code-jp/tree/release/OTF))，以及 64 个字体的[Noto Sans CJK 和 Noto Serif CJK OTFs](https://github.com/googlei18n/noto-cjk)。这个特殊的开源项目主要目的是对使用OpenType / CFF集合的环境进行压力测试，特别是 macOS (OS X) 10.8 版（即 Mountain Lion）或更高版本、iOS 7 或更高版本、Windows 10 1703 版（即创造者更新）或更高版本、使用 fontconfig 和 FreeType 2.5.0.1 版或更高版本的 Linux，以及 Adobe CS6 或更高版本的程序。

[COMMANDS.txt](COMMANDS.txt) 提供了预处理 142 个字体的OpenType/CFF 字体并合并为三个不同的 OpenType/CFF 集合的命令行。

## Super OTC ZIP 文件

**特别注意**：由于 GitHub 的文件大小上限为 100MB，故而 Super OTC 压缩文件被迫分解为三个部分。不幸的是，macOS 自带的归档工具并不支持解压分解的 ZIP 文件，因此我们建议你下载并安装 [Unarchiver](http://unarchiver.c3.cx/unarchiver) 程序。请将第三部分文件（扩展名为“.zip”，文件名为 SourceHan.ttc.zip、NotoCJK.ttc.zip 或 SourceHanNotoCJK.ttc.zip）拖入 Unarchiver 程序，或者单击文件选择特定程序解压（在 Unarchiver 安装完成后，你应该能直接双击打开第三部分的文件）。这两种方法都可以全部解压这三个部分。在 Windows 上，选择第三部分文件，在右键菜单中选择“全部解压”即可解压这三个部分。对于 Ubuntu 或其他 Linux 系统，我们建议你下载并安装 [Unarchiver 命令行工具](https://unarchiver.c3.cx/commandline)，之后执行 *unar* 命令解压第三个部分文件即可。

### Source Han

此 Super OTC 包含 78 个字体，307983900 字节，MD5 散列值为 95d976a8594af2764e33f9b8e0139192。

[Super OTC Part 1](https://github.com/adobe-fonts/source-han-super-otc/raw/master/SourceHan.ttc.z01) (89128960 字节) + [Super OTC Part 2](https://github.com/adobe-fonts/source-han-super-otc/raw/master/SourceHan.ttc.z02) (89128960 字节) + [Super OTC Part 3](https://github.com/adobe-fonts/source-han-super-otc/raw/master/SourceHan.ttc.zip) (73962052 字节)

### Noto CJK

此 Super OTC 包含 64 个字体，277560080 字节，MD5 散列值为 c3f1d474597f5345760748f34537eeb5。

[Super OTC Part 1](https://github.com/adobe-fonts/source-han-super-otc/raw/master/NotoCJK.ttc.z01) (89128960 字节) + [Super OTC Part 2](https://github.com/adobe-fonts/source-han-super-otc/raw/master/NotoCJK.ttc.z02) (89128960 字节) + [Super OTC Part 3](https://github.com/adobe-fonts/source-han-super-otc/raw/master/NotoCJK.ttc.zip) (47817104 字节)

### Source Han + Noto CJK

此 Super OTC 包含 142 个字体，308203516 字节，MD5 散列值为 hash is c01f4a60cee523104f9c936cf8a2df2f。

[Super OTC Part 1](https://github.com/adobe-fonts/source-han-super-otc/raw/master/SourceHanNotoCJK.ttc.z01) (89128960 字节) + [Super OTC Part 2](https://github.com/adobe-fonts/source-han-super-otc/raw/master/SourceHanNotoCJK.ttc.z02) (89128960 字节) + [Super OTC Part 3](https://github.com/adobe-fonts/source-han-super-otc/raw/master/SourceHanNotoCJK.ttc.zip) (73973121 字节)

## 字体安装说明

* [macOS](https://support.apple.com/en-us/HT201749)
* [Windows](https://www.microsoft.com/en-us/Typography/TrueTypeInstall.aspx)
* [基于 Linux/Unix 的系统](https://github.com/adobe-fonts/source-code-pro/issues/17#issuecomment-8967116)

## 参与项目

对于 Source Han Super OTC 更新的建议可以发送至 项目的维护者[小林剑博士](mailto:lunde@adobe.com?subject=[GitHub]%20Source%20Han%20Super%20OTC)，以备参考。

## 更多信息

关于思源字体的设计和背景的信息，请移步它们各自的仓库。

**Comment by kenlunde** [comment]
This project is somewhat experimental and for testing purposes, and I'd prefer that it matures a bit more before I start to include localized versions of its _README.md_ file. If I add one for Simplified Chinese now, there'll be an expectation to add them for the other supported languages, which creates a logistical nightmare if there are significant changes to its content. I'll therefore close the issue for now, but will consider adding localized _README.md_ files in the future.

**Comment by DrXie** [comment]
All right, I can understand, hope this immature translation can be used as a reference.

**Comment by kenlunde** [comment]
Yes, it is helpful, but a bit premature to deploy at this time. Thank you. 🥃

**Comment by DrXie** [comment]
By the way, unzipping the files in Linux is very simple. Unarchiver has command line version, just execute _unar SourceHanNotoCJK.ttc.zip_

**Comment by kenlunde** [comment]
Thank you. After asking someone to confirm the above, I modified the *README.md* file accordingly.
