### ISSUE TITLE
Using GitHub Releases

### ISSUE THREAD

**Issue by tani** [adobe-fonts/source-han-super-otc#4]
According to the README,  you're splitting file with GitHub's limitation but you could use GitHub Releases like other projects. GitHub Releases allows files under the 2GB. Could you use it? By this change we'll be able to install them without concatenating zip files and it is good for macOS users. Please consider this. Thank you.

**Comment by kenlunde** [comment]
@asciian Thank you for the suggestion. Please check the [20180125](https://github.com/adobe-fonts/source-han-super-otc/releases/tag/20180125) release that I just prepared.

**Comment by tani** [comment]
Great! Thank you for your work.

**Comment by kenlunde** [comment]
Thank you for confirming. I still need to adjust the landing page (aka _README.md_ file), which will also involve removing the split ZIP files.
