### ISSUE TITLE
Ultra OTC for general use advisable?

### ISSUE THREAD

**Issue by polarathene** [adobe-fonts/source-han-super-otc#6]
My system has Noto fonts setup(along with CJK), I've come across the Adobe Source equivalents and the Source Han Mono that Noto doesn't have it's own equivalent of.

Is the Ultra OTC suitable as a replacement for covering Noto fonts and the Source Han Mono fonts? I could also just install the Source Han Mono OTC instead separately. The Ultra OTCs only benefit really being the space savings and additional font family mappings, which a system could use instead of potentially falling back to a different font, when an application requests the Adobe or Google branded name instead?

I have not seen the Adobe Source font families used much on the web or in other software that is not Adobe, other than Source Code Pro. I assume it's the primary choice for CJK in Adobe software? Do you know how likely users are to encounter the Adobe variants? Noto is the default on some Linux distros and sometimes specified in CSS font stacks.

Main drawback here as a user I guess is effectively doubling the font list size to accomodate both variants. There also appears to be some Noto fonts that don't fall into Noto Sans/Serif groups(Music and Arabic/Urdu).

I have read your blog articles related to this repo, and noted that [this one](https://blogs.adobe.com/CCJKType/2017/04/three-multiple-family-super-otcs.html) clarifies a small difference between Source and Noto families:

>  This is because almost all of the 'sfnt' tables of the Noto CJK fonts are shared with Source Han ones.
> Note that I forced the 'cmap' tables of the Noto Serif CJK fonts to be shared with those of Source Han Serif; the former fonts lack mappings for U+2252 ≒ APPROXIMATELY EQUAL TO OR THE IMAGE OF and U+25C8 ◈ WHITE DIAMOND CONTAINING BLACK SMALL DIAMOND.

---

Do the OTCs have any drawbacks due to their larger single file size? I'm not familiar with how the OS interacts with font files or the OTC format, so perhaps it's a non-issue with I/O or lookup performance compared to individual files(maybe it even performs better?)

I have noticed in some cases, such as highlighting some text and right clicking it in the browser recently, that I can get a CPU activity spike and a bit of latency(few seconds) before the context menu is drawn with the appropriate text content/glyphs. This is without the OTC, and I assume it's related to searching through many fonts for fallback glyphs/font, on plain latin text it performs fine.

**Comment by kenlunde** [comment]
@polarathene To answer the question that is posed in the title: Yes! Ever since I started to produce these Mega and Ultra OTCs, I have been using only the Ultra OTC. As a nearly 400MB font resource that includes 216 fonts that massively share tables, it works out to just under 2MB per 65,355-glyph font. And, as long as your environment supports OTCs, to include those with a large number of fonts, there should be no issues. I us macOS, and the Ultra OTC is the ideal deployment format for these five families. As I stated in the _Source Han Mono_ repository, I am no longer able to manage this project, so please close this issue yourself.

**Comment by polarathene** [comment]
> Yes! Ever since I started to produce these Mega and Ultra OTCs, I have been using only the Ultra OTC.

Great, thanks :)

> As I stated in the Source Han Mono repository, I am no longer able to manage this project, so please close this issue yourself.

Oh... I see you just changed jobs? Congrats on the new role! Does this mean any changes to the Source/Noto fonts will not see updates to the OTC here? Or has someone at Adobe taken over that responsibility and will ensure this repo is maintained accordingly?

**Comment by kenlunde** [comment]
@polarathene Well, I didn't really change jobs, but Adobe upper-management saw fit to terminate my employment after 28+ years. Not to worry, though. My font-development skills completely transcend any open source projects to which I contributed. A bit of patience is prudent at this stage of the game. I am still using the 216-font Ultra OTC, which should speak volumes to its usefulness.

**Comment by polarathene** [comment]
That's unfortunate to hear :cry: I've seen you in various issues/projects on Github regarding fonts and read quite a few of your articles. You're an expert in the field afaik from what I've come across, I imagine the available roles are few, but I wish you all the best, your expertise in the field must be difficult to find when needed.

> I am still using the 216-font Ultra OTC, which should speak volumes to its usefulness.

I don't doubt it :) On Arch Linux `source-han-sans`/`source-han-serif`/`source-han-mono` OTCs are all packaged, and the derivative distro I use (Manjaro Linux, KDE) opts for Noto packages by default. I still need some Noto fonts that I don't think would be packaged into the Ultra OTC as they're not likely to packaged there afaik, but that font package also includes the Noto Sans/Serif fonts. 

As I am rarely involved with Adobe's design products these days and don't encounter the font elsewhere, I'll just go with the your `source-han-mono` OTC since I won't benefit from size savings unless I contribute a replacement/alternative package for my distro. Probably less of a concern on Windows/macOS(or other Linux distros) where Noto isn't your default font at install and required as a dependency over others.

For my friends in asia though, the "Source Han" fonts would be better for their localized font names.
